---
name: Publish docs via Github Pages

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --strict --force
